### get all expenses
GET http://localhost:3003/api/exp

### get Single expenses
GET http://localhost:3003/api/exp/1

### del Single expenses
DELETE http://localhost:3003/api/exp/8bec3e37-83e6-45b5-8f97-4c2b4e227a3e

### Create expenses
POST http://localhost:3003/api/exp
Content-Type:  application/json

{
  "cat": "Home",
  "amount": 3000
}

### Edit user
PUT http://localhost:3000/api/users/7e61088e-50bd-49a2-9652-36b487819216
Content-Type:  application/json

{
  "cat": "Edited",
  "amount": 0
}