### get all expenses
GET http://localhost:3003/api/exp

### get Single user
GET http://localhost:3000/api/users/b60b3fb9-e497-47f2-82b3-00e1a3386bbd

### del Single user
DELETE http://localhost:3000/api/users/1

### Create expenses
POST http://localhost:3003/api/exp
Content-Type:  application/json

{
  "cat": "Home",
  "amount": 3000
}

### Edit user
PUT http://localhost:3000/api/users/7e61088e-50bd-49a2-9652-36b487819216
Content-Type:  application/json

{
  "name": "UpdatedName",
  "town": "UpdatedTown",
  "isDriver": true
}